Repository Rudy-Menjivar/livent, pull requests merged in 2020-11, with the labels that each got.

#7 added another row to table
  index.html
Labels: enhancement

#25 Incorporated predictHQ API, & started working with page elements
  assets/script.js
  index.html
Labels: enhancement

#27 Added clear-all button & search count radio inputs
  index.html
Labels: enhancement

#32 Updated radio buttons & replaced id with name
  index.html
Labels: enhancement

#33 loop added for radio dom selection for rendering the selected number …
  assets/script.js
Labels: enhancement

#37 new card created for search results data
  index.html
Labels: enhancement

#42 Enhancements added to render title, date, categories and lat/longitud…
  assets/script.js
Labels: enhancement

#44 removed clear() from button search to correct search results
  assets/script.js
Labels: bug

#46 Corrected labels of lats & longs as they were backwards
  assets/script.js
Labels: bug

#49 Findmebutton
  assets/script.js
  assets/stylesheet.css
  index.html
Labels: enhancement

#50 introduced bulma to styling
  index.html
Labels: enhancement

#53 Clear previous search results after every search
  assets/script.js
  assets/stylesheet.css
Labels: bug

#56 Invisible els
  assets/script.js
  index.html
Labels: enhancement

#57 Geoloc request
  assets/script.js
  index.html
Labels: enhancement

#67 separate README update
  README.MD
Labels: documentation

#70 Search updates
  assets/script.js
  index.html
Labels: enhancement

#69 set card visibility to hidden & moved script to script file
  index.html
Labels: bug

#77 Distance search
  assets/script.js
  index.html
Labels: enhancement

#79 Styles css
  assets/stylesheet.css
  index.html
Labels: enhancement

#78 changed hero banner to a background img
  index.html
Labels: enhancement

#80 adding image to repo
  assets/pexels-sebastian-ervi-1763075.jpg
Labels: enhancement
